FROM node:20.9-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma

RUN npm ci

COPY . .

RUN npx prisma generate
RUN npm run build

EXPOSE 3001

ENTRYPOINT ["sh", "-c", "npx prisma generate && npx prisma migrate deploy && npm start"]

